version: 2
updates:
  # Maintain dependencies for npm (Playwright/Testing)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for Composer (Drupal)
#  - package-ecosystem: "composer"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 10
  # Maintain GitHub Actions (Workflows)
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "monthly"